In [1]:
from torch import nn
import torch
import torchvision
from torch.utils.data import DataLoader
from torchvision import transforms
import numpy as np

In [2]:
# Using torch.Tensor
t = torch.Tensor([[1,2,3],[3,4,5]])
print(f"Created Tensor Using torch.Tensor:\n{t}")

# Using torch.randn
t = torch.randn(3, 5)
print(f"Created Tensor Using torch.randn:\n{t}")

# using torch.[ones|zeros](*size)
t = torch.ones(3, 5)
print(f"Created Tensor Using torch.ones:\n{t}")
t = torch.zeros(3, 5)
print(f"Created Tensor Using torch.zeros:\n{t}")

# using torch.randint - a tensor of size 4,5 with entries between 0 and 10(excluded) 
t = torch.randint(low = 0,high = 10,size = (4,5))
print(f"Created Tensor Using torch.randint:\n{t}")

# Using from_numpy to convert from Numpy Array to Tensor 
a = np.array([[1,2,3],[3,4,5]])
t = torch.from_numpy(a)
print(f"Convert to Tensor From Numpy Array:\n{t}")

# Using .numpy() to convert from Tensor to Numpy array 
t = t.numpy()
print(f"Convert to Numpy Array From Tensor:\n{t}")

Created Tensor Using torch.Tensor:
tensor([[1., 2., 3.],
        [3., 4., 5.]])
Created Tensor Using torch.randn:
tensor([[-0.3058,  0.4658,  0.9589, -1.1946,  0.0468],
        [ 1.1972,  0.4946, -0.7867,  0.3801, -0.1841],
        [-0.4104,  1.7376, -0.3540,  0.5128,  1.1579]])
Created Tensor Using torch.ones:
tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
Created Tensor Using torch.zeros:
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
Created Tensor Using torch.randint:
tensor([[1, 2, 9, 5, 7],
        [0, 3, 2, 4, 0],
        [9, 1, 7, 2, 7],
        [3, 2, 0, 4, 0]])
Convert to Tensor From Numpy Array:
tensor([[1, 2, 3],
        [3, 4, 5]])
Convert to Numpy Array From Tensor:
[[1 2 3]
 [3 4 5]]


In [3]:
A = torch.randn(3,4)
W = torch.randn(4,2)
# Multiply Matrix A and W
t = A.mm(W)
print(f"Created Tensor t by Multiplying A and W:\n{t}")
# Transpose Tensor t
t = t.t()
print(f"Transpose of Tensor t:\n{t}")
# Square each element of t
t = t**2
print(f"Square each element of Tensor t:\n{t}")
# return the size of a tensor
print(f"Size of Tensor t using .size():\n{t.size()}")

Created Tensor t by Multiplying A and W:
tensor([[ 2.6782,  0.6292],
        [ 0.9754, -2.8601],
        [ 0.4682,  1.7653]])
Transpose of Tensor t:
tensor([[ 2.6782,  0.9754,  0.4682],
        [ 0.6292, -2.8601,  1.7653]])
Square each element of Tensor t:
tensor([[7.1728, 0.9514, 0.2192],
        [0.3959, 8.1800, 3.1161]])
Size of Tensor t using .size():
torch.Size([2, 3])


# The nn.Module

In [4]:
class myNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Define all Layers Here
        self.lin1 = nn.Linear(784, 30)
        self.lin2 = nn.Linear(30, 10)

    def forward(self, x):
        # Connect the layer Outputs here to define the forward pass
        x = self.lin1(x)
        x = self.lin2(x)
        return x

In [5]:
x = torch.randn((100,784))
model = myNeuralNet()
model(x).size()

torch.Size([100, 10])

In [6]:
class myCrazyNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Define all Layers Here
        self.lin1 = nn.Linear(784, 30)
        self.lin2 = nn.Linear(30, 784)
        self.lin3 = nn.Linear(30, 10)
        
    def forward(self, x):
        # Connect the layer Outputs here to define the forward pass
        x_lin1 = self.lin1(x)
        x_lin2 = x + self.lin2(x_lin1)
        x_lin2 = self.lin1(x_lin2)
        x = self.lin3(x_lin2)
        return x

In [7]:
x = torch.randn((100,784))
model = myCrazyNeuralNet()
model(x).size()

torch.Size([100, 10])

# A word about Layers

In [8]:
from torch import nn

class myCustomLinearLayer(nn.Module):
    def __init__(self,in_size,out_size):
        super().__init__()
        self.weights = nn.Parameter(torch.randn(in_size, out_size))
        self.bias = nn.Parameter(torch.zeros(out_size))

    def forward(self, x):
        return x.mm(self.weights) + self.bias

In [9]:
class myCustomNeuralNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Define all Layers Here
        self.lin1 = myCustomLinearLayer(784,10)
        
    def forward(self, x):
        # Connect the layer Outputs here to define the forward pass
        x = self.lin1(x)
        return x

In [10]:
x = torch.randn((100,784))
model = myCustomNeuralNet()
model(x).size()

torch.Size([100, 10])

# Conv2d Layer

In [11]:
conv_layer = nn.Conv2d(in_channels = 3, out_channels = 64, kernel_size = (3,3), stride = 1, padding=1)

In [12]:
x = torch.randn((100,3,24,24))
conv_layer(x).size()

torch.Size([100, 64, 24, 24])

# Datasets

In [13]:
traindir = "/home/rahul/projects/compvisblog/data/train/"

In [14]:
t = transforms.Compose([
        transforms.Resize(size=256),
    transforms.CenterCrop(size=224),
        transforms.ToTensor()])

train_dataset = torchvision.datasets.ImageFolder(root=traindir,transform=t)

print("Num Images in Dataset:", len(train_dataset))
print("Example Image and Label:", train_dataset[2])

Num Images in Dataset: 847
Example Image and Label: (tensor([[[0.1882, 0.2118, 0.2118,  ..., 0.1686, 0.1569, 0.1725],
         [0.1882, 0.2039, 0.2275,  ..., 0.1882, 0.1765, 0.1961],
         [0.1725, 0.1529, 0.1843,  ..., 0.1020, 0.1176, 0.1569],
         ...,
         [0.1451, 0.1412, 0.1333,  ..., 0.1176, 0.1137, 0.1059],
         [0.1255, 0.1216, 0.1137,  ..., 0.0980, 0.0980, 0.0980],
         [0.1333, 0.1294, 0.1255,  ..., 0.0980, 0.0980, 0.0941]],

        [[0.4784, 0.4902, 0.4863,  ..., 0.4941, 0.4902, 0.4980],
         [0.4980, 0.5020, 0.5216,  ..., 0.4941, 0.4824, 0.5020],
         [0.5020, 0.4863, 0.5098,  ..., 0.4549, 0.4588, 0.4902],
         ...,
         [0.4588, 0.4549, 0.4471,  ..., 0.4078, 0.4000, 0.3922],
         [0.4353, 0.4314, 0.4275,  ..., 0.3961, 0.3843, 0.3804],
         [0.4431, 0.4353, 0.4314,  ..., 0.3961, 0.3882, 0.3843]],

        [[0.8157, 0.8235, 0.8118,  ..., 0.8314, 0.8314, 0.8784],
         [0.8627, 0.8627, 0.8706,  ..., 0.8118, 0.8118, 0.8471],
     

In [15]:
for i in range(0,len(train_dataset)):
    image ,label = train_dataset[i]
    print(image,label)
    break

tensor([[[0.6157, 0.6196, 0.6118,  ..., 0.6157, 0.6157, 0.6118],
         [0.6392, 0.6275, 0.6118,  ..., 0.6275, 0.6314, 0.6353],
         [0.6353, 0.6157, 0.6078,  ..., 0.6431, 0.6431, 0.6588],
         ...,
         [0.6980, 0.6706, 0.6431,  ..., 0.5333, 0.5686, 0.5882],
         [0.6863, 0.6275, 0.6235,  ..., 0.6196, 0.6039, 0.6039],
         [0.6118, 0.5490, 0.5922,  ..., 0.6039, 0.6196, 0.5647]],

        [[0.7098, 0.7098, 0.7059,  ..., 0.7059, 0.7098, 0.7059],
         [0.7255, 0.7098, 0.7020,  ..., 0.7137, 0.7176, 0.7216],
         [0.7137, 0.7020, 0.6980,  ..., 0.7216, 0.7255, 0.7333],
         ...,
         [0.7255, 0.7059, 0.6627,  ..., 0.5686, 0.5961, 0.6235],
         [0.7137, 0.6627, 0.6588,  ..., 0.6549, 0.6353, 0.6314],
         [0.6353, 0.5804, 0.6314,  ..., 0.6431, 0.6510, 0.5922]],

        [[0.8196, 0.8275, 0.8275,  ..., 0.8196, 0.8196, 0.8157],
         [0.8275, 0.8235, 0.8157,  ..., 0.8196, 0.8235, 0.8275],
         [0.8157, 0.8196, 0.8196,  ..., 0.8314, 0.8275, 0.

In [16]:
train_dataloader = DataLoader(train_dataset,batch_size = 64, shuffle=True, num_workers=10)
for image_batch, label_batch in train_dataloader:
    print(image_batch.size(),label_batch.size())
    break

torch.Size([64, 3, 224, 224]) torch.Size([64])


# Custom Dataset

In [17]:
from glob import glob
from PIL import Image
from torch.utils.data import Dataset

class customImageFolderDataset(Dataset):
    """Custom Image Loader dataset."""
    def __init__(self, root, transform=None):
        """
        Args:
            root (string): Path to the images organized in a particular folder structure.
            transform: Any Pytorch transform to be applied
        """
        # Get all image paths from a directory
        self.image_paths = glob(f"{root}/*/*")
        # Get the labels from the image paths
        self.labels = [x.split("/")[-2] for x in self.image_paths]
        # Create a dictionary mapping each label to a index from 0 to len(classes).
        self.label_to_idx = {x:i for i,x in enumerate(set(self.labels))}
        self.transform = transform
        
    def __len__(self):
        # return length of dataset
        return len(self.image_paths)
      
    def __getitem__(self, idx):
        # open and send one image and label
        img_name = self.image_paths[idx]
        label = self.labels[idx]
        image = Image.open(img_name)
        if self.transform:
            image = self.transform(image)
        return image,self.label_to_idx[label]

# Custom Dataloaders

In [18]:
class BiLSTM(nn.Module):
    def __init__(self):
        super().__init__()
        self.hidden_size = 64
        drp = 0.1
        max_features, embed_size = 10000,300
        self.embedding = nn.Embedding(max_features, embed_size)
        self.lstm = nn.LSTM(embed_size, self.hidden_size, bidirectional=True, batch_first=True)
        self.linear = nn.Linear(self.hidden_size*4 , 64)
        self.relu = nn.ReLU()
        self.dropout = nn.Dropout(drp)
        self.out = nn.Linear(64, 1)


    def forward(self, x):
        h_embedding = self.embedding(x)
        h_embedding = torch.squeeze(torch.unsqueeze(h_embedding, 0))
        
        h_lstm, _ = self.lstm(h_embedding)
        avg_pool = torch.mean(h_lstm, 1)
        max_pool, _ = torch.max(h_lstm, 1)
        conc = torch.cat(( avg_pool, max_pool), 1)
        conc = self.relu(self.linear(conc))
        conc = self.dropout(conc)
        out = self.out(conc)
        return out

In [19]:
model = BiLSTM()
input_batch_1 = torch.randint(low = 0,high = 10000, size = (100,10))
input_batch_2 = torch.randint(low = 0,high = 10000, size = (100,25))
print(model(input_batch_1).size())
print(model(input_batch_2).size())

torch.Size([100, 1])
torch.Size([100, 1])


### Custom Dataset

In [20]:
class CustomTextDataset(Dataset):
    '''
    Simple Dataset initializes with X and y vectors
    We start by sorting our X and y vectors by sequence lengths
    '''
    def __init__(self,X,y=None):
        self.data = list(zip(X,y))
        # Sort by length of first element in tuple
        self.data = sorted(self.data, key=lambda x: len(x[0]))
        
    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

In [21]:
import numpy as np
train_data_size = 1024
sizes = np.random.randint(low=50,high=300,size=(train_data_size,))

X = [np.random.randint(0,10000, (sizes[i])) for i in range(train_data_size)]
y = np.random.rand(train_data_size).round()

In [22]:
print((X[0],y[0]))

(array([ 167, 3822, 4885,  246, 6351, 3738, 4192, 6041, 8267,  238, 8960,
       9112, 8563, 4342, 6757, 4193, 4188, 8421, 1942, 8743, 3062, 8293,
       5065, 1461, 5614, 8068, 7612, 2164, 7469, 5242, 4299, 5794, 9966,
       3385, 7728, 8258, 2627, 1376, 5062, 1986, 1505, 2140, 4468, 3175,
       5517, 5646, 6707, 6097, 7448, 9749, 3755, 4422, 3349, 9645, 4058,
       6967, 9123, 1997, 1939, 6086, 9079, 4669, 2787, 9958, 7377,  252,
       9239, 6900, 8168, 9174, 8561, 3745, 5906, 1761, 1425, 7515, 7478,
       2004, 9641, 8321, 3508, 1280, 7079, 2780, 3423,  974, 4520, 7069,
       9194, 2634, 8392, 1912, 2015, 1260, 7777, 6938, 1254, 2778, 5904,
       5485, 5106, 9698, 6013, 4624, 1251, 3259, 3732, 3518, 3740, 3589,
       6537, 9744, 4021, 1980, 6451, 7411, 2977, 6496, 3492, 7167, 2686,
       2677, 6791, 1186, 3977, 2770, 5897, 2208, 6885, 5450,  677, 3481,
       5563, 9767, 7090, 8707, 2419, 2022, 7519, 5979, 8901, 4643, 1795,
       3213, 3721, 5854,  405, 6209, 3998, 6707, 1

If we now use a simple Dataloader on top of this:


In [23]:
train_dataset = CustomTextDataset(X,y)

In [24]:
train_dataloader = DataLoader(train_dataset,batch_size = 64, shuffle=False, num_workers=10)

In [25]:
for xb,yb in train_dataloader:
    print(xb.size(),yb.size())

RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/rahul/anaconda3/envs/pyt/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/rahul/anaconda3/envs/pyt/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/rahul/anaconda3/envs/pyt/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "/home/rahul/anaconda3/envs/pyt/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "/home/rahul/anaconda3/envs/pyt/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 64, in default_collate
    return default_collate([torch.as_tensor(b) for b in batch])
  File "/home/rahul/anaconda3/envs/pyt/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: stack expects each tensor to be equal size, but got [50] at entry 0 and [51] at entry 2


In [26]:
def collate_text(batch):
    # get text sequences in batch
    data = [item[0] for item in batch]
    # get labels in batch
    target = [item[1] for item in batch]
    # get max_seq_length in batch
    max_seq_len = max([len(x) for x in data])
    # pad text sequences based on max_seq_len
    data = [np.pad(p, (0, max_seq_len - len(p)), 'constant') for p in data]
    # convert data and target to tensor
    data = torch.LongTensor(data)
    target = torch.LongTensor(target)
    return [data, target]

In [27]:
train_dataloader = DataLoader(train_dataset,batch_size = 64, shuffle=False, 
                              num_workers=10,collate_fn = collate_text)
for xb,yb in train_dataloader:
    print(xb.size(),yb.size())

torch.Size([64, 66]) torch.Size([64])
torch.Size([64, 84]) torch.Size([64])
torch.Size([64, 98]) torch.Size([64])
torch.Size([64, 110]) torch.Size([64])
torch.Size([64, 126]) torch.Size([64])
torch.Size([64, 141]) torch.Size([64])
torch.Size([64, 158]) torch.Size([64])
torch.Size([64, 173]) torch.Size([64])
torch.Size([64, 190]) torch.Size([64])
torch.Size([64, 204]) torch.Size([64])
torch.Size([64, 222]) torch.Size([64])
torch.Size([64, 240]) torch.Size([64])
torch.Size([64, 255]) torch.Size([64])
torch.Size([64, 270]) torch.Size([64])
torch.Size([64, 287]) torch.Size([64])
torch.Size([64, 299]) torch.Size([64])


# Neural Network training code

# Losses

In [28]:
class myClassificationNet(nn.Module):
    def __init__(self):
        super().__init__()
        # Define all Layers Here
        self.lin = nn.Linear(784, 10)
        self.logsoftmax = nn.LogSoftmax(dim=1)

    def forward(self, x):
        # Connect the layer Outputs here to define the forward pass
        x = self.lin(x)
        x = self.logsoftmax(x)
        return x

In [29]:
# some random input:

X = torch.randn(100,784)
y = torch.randint(low = 0,high = 10,size = (100,))

In [30]:
model = myClassificationNet()
preds = model(X)

In [31]:
criterion = nn.NLLLoss()
loss = criterion(preds,y)

In [32]:
loss

tensor(2.4242, grad_fn=<NllLossBackward>)

# Custom Loss

In [33]:
def custom_mse_loss(output,target):
    loss = torch.mean((output - target)**2)     
    return loss

In [34]:
criterion = nn.NLLLoss()
pytorchNLLloss = criterion(preds,y)

In [ ]:
def CustomNLLLossFunc(x, y):
    log_prob = -1.0 * x
    loss = log_prob.gather(1, y.unsqueeze(1))
    loss = loss.mean()
    return loss

In [ ]:
CustomNLLLossFuncLoss = CustomNLLLossFunc(preds,y)

In [ ]:
class CustomNLLLoss(nn.Module):
    def __init__(self):
        super().__init__()
    def forward(self, x, y):
        # x should be output from LogSoftmax Layer 
        log_prob = -1.0 * x
        # Get log_prob based on y class_index as loss=-mean(ylogp)
        loss = log_prob.gather(1, y.unsqueeze(1))
        loss = loss.mean()
        return loss

In [ ]:
criterion = CustomNLLLoss()
CustomNLLLossClass = criterion(preds,y)

In [ ]:
pytorchNLLloss

In [ ]:
CustomNLLLossFuncLoss

In [ ]:
CustomNLLLossClass

# Optimizer

In [ ]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.01, betas=(0.9, 0.999))

# Using GPU

In [ ]:
# Whether to train on a gpu
train_on_gpu = torch.cuda.is_available()
print(f'Train on gpu: {train_on_gpu}')# Number of gpus
if train_on_gpu:
    gpu_count = torch.cuda.device_count()
    print(f'{gpu_count} gpus detected.')
    if gpu_count > 1:
        multi_gpu = True
    else:
        multi_gpu = False
if train_on_gpu:
    model = model.to('cuda')
if multi_gpu:
    model = nn.DataParallel(model)